# Generated by Django 4.1.2 on 2022-11-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathmadness_app', '0004_book_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
